config/routes.rb
Rails.application.routes.draw do
  resources :musicians

  root 'musicians#index'

  get '/client_token' => 'musicians#client_token'

  get '/termsandprivacy' => 'musicians#terms'

  post '/checkout' => 'musicians#checkout'

end

app/models/musician.rb
class Musician < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_cache_headers

  private

  def set_cache_headers
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
  before_action :set_musician, only: [:show, :edit, :update, :destroy]

  # GET /musicians
  # GET /musicians.json
  def index
    @musicians = Musician.order(:id).all

    # generate client token, to be grabbed by js in UI
    @client_token = Braintree::ClientToken.generate

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @musicians }
      format.json {render :json=>@musicians}
    end
  end

  # GET /musicians/1
  # GET /musicians/1.json
  def show
  end

  # GET /musicians/new
  def new
    @musician = Musician.new
  end

  # GET /musicians/1/edit
  def edit
  end

  # POST /musicians
  # POST /musicians.json
  def create
  end

  # PATCH/PUT /musicians/1
  # PATCH/PUT /musicians/1.json
  def update
    # find our musician
    @musician = Musician.find(params[:id])

    # set the status to true
    @musician.update_attributes(:status => true)
    @musician.save

    respond_to do |format|
      format.js {render inline: "location.reload();" }
    end
  end

  # DELETE /musicians/1
  # DELETE /musicians/1.json
  def destroy
    @musician.destroy
    respond_to do |format|
      format.html { redirect_to musicians_url, notice: 'Musician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def checkout
    # do the money thing
    nonce = params[:payment_method_nonce]

    result = Braintree::Transaction.sale(
      :amount => "50.00",
      :payment_method_nonce => nonce
      )

    if result.success?
      # find our musician
      @musician = Musician.find(params[:id])

      # set the status to true
      @musician.update_attributes(:status => true)

      # if the donor has opted in, save their name to display on the map
      if params[:donorname] && params[:include]
        @musician.update_attributes(:sponsor => params[:donorname])
      end
      @musician.save

      # send an email notifying of the donation
      DonationMailer.new_donor(params[:donoremail],params[:donorname],params[:include])

      flash[:notice] = "Thanks for donating! Look for a concert ticket in your inbox – see you on the 18th!"
      redirect_to root_url
    else
      result.errors.each do |error|
        puts error.attribute
        puts error.code
        puts error.message
      end

      flash[:notice] = "Sorry, something went wrong! Please try again."

      redirect_to root_url
    end
  end

  def terms
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_musician
      @musician = Musician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def musician_params
      params.require(:musician).permit(:instrument, :status, :sponsor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musicians_helper.rb
module MusiciansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sponsor a Musician: Seattle Collaborative Orchestra</title>

  <meta name="description" content="An unusual fundraising campaign for an inter-generational orchestra.">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application" %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/musicians/_form.html.erb
<%= form_for(@musician) do |f| %>
  <% if @musician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@musician.errors.count, "error") %> prohibited this musician from being saved:</h2>

      <ul>
      <% @musician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :instrument %><br>
    <%= f.text_field :instrument %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :sponsor %><br>
    <%= f.text_field :sponsor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musicians/edit.html.erb
<h1>Editing musician</h1>

<%= render 'form' %>

<%= link_to 'Show', @musician %> |
<%= link_to 'Back', musicians_path %>

app/views/musicians/index.html.erb
<% if flash[:notice] %>
  <div class="notice">
    <div class="close-button">&times;</div>

    <h3><%= flash[:notice] %></h3>
  </div>
<% end %>

<div id="header">
  <div class="wrapper">
    <h1>SCO: Sponsor a Musician</h1>

    <p>On November 18, we will be presenting you with an <a class="link" href="http://livemusicproject.org/event/seattle-collaborative-orchestra-listen-to-the-girls/">innovative concert</a>. Our orchestra is inter-generational, a collaboration between Seattle-area high school and college students, volunteers from the community, and professionals from premier ensembles like the Seattle Symphony.</p>

    <p>We are asking you, our community, to help take part in this event. For &#36;50, you can sponsor a student or volunteer musician, and get a complimentary ticket to our concert. Here&apos;s the twist. If all musicians are sponsored by the day of the concert, the money will go to the musicians. If not, the money will go to the orchestra&apos;s general fund. Either way, you will be supporting our exciting musical collaboration. Find a musician on the stage map below, and click to sponsor!</p>

    <div class="counter">
      <div id="days"></div>

      <h1><span id="numSponsored"></span></h1>
      musicians sponsored
    </div>
  </div>
</div>

<%= content_tag "div", id: "orchestra", data: {url: root_url} do %>
  <div class="popup"></div>
<% end %>

<div id="checkout">
  <div class="close-button">&times;</div>

  <div class="information">
    <h3>Test content</h3>
  </div>

  <form id="checkout-form" method="post" action="/checkout">
    <div id="details">
      <input type="text" name="donorname" placeholder="Name">
      <input type="email" name="donoremail" placeholder="Email Address" required>
      <input type="checkbox" name="include">
      <label for="include">Show my name in the list of donors</label>
    </div>
    <div id="payment-form"></div>
    <button type="submit">Sponsor for $50</button>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type="hidden" id="id-field" name="id" value="">
  </form>
</div>

<div id="lightbox"></div>

<div id="footer">
  
  <div class="text">
    <a href="http://livemusicproject.org" title="The Live Music Project" alt="The Live Music Project"><%= image_tag "LMP.png" %></a>

    <div class="socialmedia">
      <a href="https://twitter.com/share" class="twitter-share-button" data-text="Sponsor an SCO musician by 11/18!" data-via="LiveMusicProj" data-related="LiveMusicProj" data-count="none">Tweet</a>
      <div class="fb-share-button" data-href="https://orchestral.herokuapp.com" data-layout="button"></div>
    </div>
    
    <p>&copy; 2015 The Live Music Project. The Seattle Collaborative Orchestra is a 501(c)3 non-profit organization. All donations are tax-deductible and are paid directly to the orchestra.</p>
    <p>Contact us: <a class="link" href="mailto:info@seattlecollaborativeorchestra.org">info@seattlecollaborativeorchestra.org</a> | <a class="link" href="/termsandprivacy">Terms of use</a></p>
  </div>

</div>

<!-- Twitter share button -->
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

<!-- Facebook share button -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script src="https://js.braintreegateway.com/v2/braintree.js"></script>

<script type="text/javascript">

  // fetches client token from server
  braintree.setup('<%= @client_token %>', "dropin", {
    container: "payment-form"
  });


  var musicians = $.getJSON( $('#orchestra').data('url' + '.json'), function() { 
    renderMusicians(musicians.responseJSON);

    $(window).resize( function() {
      $('#orchestra').empty();
      renderMusicians(musicians.responseJSON);
    });
  });

  // bind clicks to open payment modal
  $('.sponsor').click( function() {
    var id =  $($(this).parent()[0]).attr('class');

    launchPayments(id);
  });

  // bind clicks to close payment modal
  $('.close-button').click(function() {
      $('#lightbox').hide();
      $(this).parent().hide();
      $('body').css('overflow', 'auto');
  });
</script>

<!-- Google Analytics tracking -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49390947-2', 'auto');
  ga('send', 'pageview');

</script>

app/views/musicians/new.html.erb
<h1>New musician</h1>

<%= render 'form' %>

<%= link_to 'Back', musicians_path %>

app/views/musicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Instrument:</strong>
  <%= @musician.instrument %>
</p>

<p>
  <strong>Status:</strong>
  <%= @musician.status %>
</p>

<p>
  <strong>Sponsor:</strong>
  <%= @musician.sponsor %>
</p>

<%= link_to 'Edit', edit_musician_path(@musician) %> |
<%= link_to 'Back', musicians_path %>

app/views/musicians/terms.html.erb
<div class="return">
	<%= link_to "← Return", root_url, :class => "link" %>
</div>

<div class="copy">
	<h2>Refund policy</h2>

	<p>If you believe you have made a donation in error, please contact us at <a class="link" href="mailto:info@seattlecollaborativeorchestra.org">info@seattlecollaborativeorchestra.org</a> and we will refund your donation.</p>

	<h2>Privacy policy</h2>

	<p>Your name and email address are collected for the purpose of processing your donation. We will never disclose your personal information without your explicit consent.</p>

	<h2>Terms and Conditions ("Terms")</h2>

	<p>Last updated: November 10, 2015</p>

	<p>Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using the <a href="https://orchestral.herokuapp.com/" class="link">https://orchestral.herokuapp.com/</a> website (the "Service") operated by The Live Music Project ("us", "we", or "our").</p>

	<p>Your access to and use of the Service is conditioned upon your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who wish to access or use the Service.</p>

	<p>By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you do not have permission to access the Service.</p>

	<h2>Intellectual Property</h2>

	<p>The Service and its original content, features and functionality are and will remain the exclusive property of The Live Music Project and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of The Live Music Project.</p>

	<h2>Links To Other Web Sites</h2>

	<p>Our Service may contain links to third party web sites or services that are not owned or controlled by The Live Music Project.</p>

	<p>The Live Music Project has no control over, and assumes no responsibility for the content, privacy policies, or practices of any third party web sites or services. We do not warrant the offerings of any of these entities/individuals or their websites.</p>

	<p>You acknowledge and agree that The Live Music Project shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such third party web sites or services.</p>

	<p>We strongly advise you to read the terms and conditions and privacy policies of any third party web sites or services that you visit.</p>

	<h2>Indemnification</h2>

	<p>You agree to defend, indemnify and hold harmless The Live Music Project and its licensee and licensors, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees), resulting from or arising out of a) your use and access of the Service, or b) a breach of these Terms.</p>

	<h2>Limitation Of Liability</h2>

	<p>In no event shall The Live Music Project, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.</p>

	<h2>Disclaimer</h2>

	<p>Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or course of performance.</p>

	<p>The Live Music Project its subsidiaries, affiliates, and its licensors do not warrant that a) the Service will function uninterrupted, secure or available at any particular time or location; b) any errors or defects will be corrected; c) the Service is free of viruses or other harmful components; or d) the results of using the Service will meet your requirements.</p>

	<h2>Exclusions</h2>

	<p>Some jurisdictions do not allow the exclusion of certain warranties or the exclusion or limitation of liability for consequential or incidental damages, so the limitations above may not apply to you.</p>

	<h2>Governing Law</h2>

	<p>These Terms shall be governed and construed in accordance with the laws of Washington, United States, without regard to its conflict of law provisions.</p>

	<p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have had between us regarding the Service.</p>

	<h2>Changes</h2>

	<p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will provide at least 60 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>

	<p>By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use the Service.</p>

	<h2>Contact Us</h2>

	<p>If you have any questions about these Terms, please contact us: <a href="info@livemusicproject.org" class="link">info@livemusicproject.org</a>.</p>
</div>